### ISSUE TITLE
question about figure8

### ISSUE THREAD

**Issue by 1456416403** [msho-student/WikiWhy#5]
First of all, congratulations on your paper being accepted, and thank you for your open source code,
I would like to ask why in the example in Figure 8 in the appendix, the annotator needs to choose one of the four questions to explain, and where do these four options come from?

**Comment by matt-seb-ho** [comment]
Thank you for the kind words! 

The interface for collecting explanations were hand made templates that ask for the intermediate steps between [CAUSE] and [EFFECT]. 

We included multiple ways of phrasing the same question because depending on how the [CAUSE] and [EFFECT] were phrased from the previous data collection stage, certain phrasings may make more grammatical sense than others. Additionally, we found that annotators sometimes misunderstood their task, and so we hypothesize that including alternate phrasings can help make the requirements more clear.

Hope this answers your questions!

**Comment by 1456416403** [comment]
thank you very much!!
